name: Release APWorld
on:
    push:
        tags:
            - "**"
jobs:
    release:
        uses: Eijebong/ap-actions/.github/workflows/release-apworld.yml@main
        with:
            apworld-path: tmc
            ap-version: "0.6.7-rc1"
            python-version: "3.11"
